### ISSUE TITLE
Issuse in pickSPUser Widget

### ISSUE THREAD

**Issue by hemalmoss** [purtuga/SPWidgets#21]
Hi,
I am trying to use the pickSPUser Widget but it is giving me issue when I select some user. for such users onPickUser function is not getting fired and the selected users stays into the input text box rather then going up with other users names.

Those users then later works fine after first time. (i.e. lets say i have a user abc for whom i face issue, then if i refresh the page and then again select abc then it works fine but not for the first time).

I was able to reproduce this in the demo page present in the solution also.

Please help me in resolving this issue. I propose to use this and now it does not work correctly.

**Comment by nafeeswht** [comment]
It's true that the majority of the first times are held in a coffee store. Such a location is a good idea since it has within built conversation inside it. So with regards to the greatest spots for any night to consider here tend to be another few.	http://www.bestdatingadviceformen.net/

**Comment by nafeeswht** [comment]
Likely to something entertaining about the first date is unquestionably a great place since it will leave an extended lasting impact. Getting towards the club a while before the show begin is a terrific way to get to understand your day and futher appreciate your pleasure time collectively. If you'll be able to joke and revel in your time in your date you're more compared to guaranteed.
http://www.herpesdatinguk.net/

**Comment by nafeeswht** [comment]
Once we tend to any or all apprehend, fashion in many cases are terribly tough to follow along with. In a good trade where ever one colour, material or even pattern in many cases are insanely hot about a minute and totally out subsequent, there's small doubt which maintaining is not any straight ahead task. Not to worry, we're here to help you type via all the newest fashion information and developments and maintain you attempting stylish.
http://www.fashionartmusic.org/

**Comment by nafeeswht** [comment]
If you're within style, you will probably can observe this the whole world enjoys Style Week like it is Holidays. You're likely to comprehend why they'll holiday over their unique base looking to get some front-row Harley chair and ogling within the extremely options.
http://www.fashionschoenen.org/

**Comment by nafeeswht** [comment]
Fashion allows us to know plenty around the someone, the way in which that they liven up, that these people place their own attire within concert suggests an individual they are actually each day time. Possibly even people that claim not to ever things to see happy the way in which that these people feel nevertheless show an account concerning who they are really as nicely as what we should play the role of. http://www.fashionsmart.org/
