### ISSUE TITLE
SPControl Upload - how to use for dummies?

### ISSUE THREAD

**Issue by Critzesl** [purtuga/SPWidgets#31]
I apologize for the noob question but I'm new to this kind of SharePoint customization and I don't quite understand how to set up the control upload widget in my code. 

I have a custom newform.aspx page where I want to have the file upload button. This page is calling a script file and I understand at bare minimum I need to have something like $("div.file_upload").SPControlUpload({ listName: "Shared Documents" }); included in my script in order to link to the plugin, but I don't understand what html elements I will need to add to my aspx page to make that work and I don't get where that script line should be going (i.e. on click of a button? or just in document.ready()?). I tried checking the demo page but I confess I was a bit overwhelmed when looking at the source.

Can you provide a basic dummy-version example with all parts detailed? For example:
"This is what you'd drop into your aspx page: <div id='upload'></div>"
"This is what would then go in your script file in the document.ready() function: $("#upload").SPControlUpload({ listName: "Shared Documents" });"

Thanks so much!

**Comment by nmn-id** [comment]
Hi purtuga,

Can you show the implementation of SPControlUpload Step by step

or with some sample Demos?


Mohan.N

**Comment by purtuga** [comment]
@nmn-id Have you looked at this usage example in the documentation?
https://github.com/purtuga/SPWidgets/blob/master/documentation/SPWidgets.md#usage

The steps are detailed above in my first response to this thread.

**Comment by nmn-id** [comment]
Hi,

Below is my code which I am using in CEWP in O365

But how I will pass my file here?

<script src="/sites/hrssdev/jquery/Upld/jquery.SPWidgets.js"></script> 

<script src="/sites/hrssdev/jquery/Upld/jquery.SPWidgets.min.js"></script> 

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script>


$(document).ready(function(){

alert("Welcome to SPControlupload");
         
$("#file_upload").SPControlUpload({ listName: "Shared
Documents" });
    });

</script>


<div id="file_upload"> Select File
   </div>

**Comment by purtuga** [comment]
This is a closed issue. Can you open up a new one that details your
specific trouble?

On Saturday, May 9, 2015, nmn-id <notifications@github.com> wrote:

> Hi,
>
> Below is my code which I am using in CEWP in O365
>
> But how I will pass my file here?
>  Select File
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/purtuga/SPWidgets/issues/31#issuecomment-100469325>.
>


-- 
Paul T.

-- Sent from Mobile

**Comment by MarioVanDenEijnde** [comment]
Hello Purtuga,

I have the following code below: But my page shows empty.
Questions:
- What should I see?
- How do I select the document to upload?
Thanks in advance.

<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Untitled 1</title>
<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/redmond/jquery-ui.css" />
</head>

<body>

<div id="file_upload"></div>

<script type="text/javascript" src='https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js'></script>
<script type="text/javascript" src='https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js'></script>
<script src="/Scripts/jquery.SPServices-2014.01.min.js"></script>
<script type="text/javascript" src='/scripts/jquery.SPWidgets.min.js'></script>
<script type="text/javascript">
$(document).ready(function(){
     $("div.file_upload").SPControlUpload({ listName: "{2651C49E-0709-4093-B497-7C66D42566A2}" });
});
</script>

</body>

</html>

Kind regards,
Mario

**Comment by purtuga** [comment]
Can you open a new issue instead of using this old one?Also: your code did not come through.  Take a look at github markdown format to know how to do it. 
Paul
-- sent from mobile
