### ISSUE TITLE
How to choose a differente listName por the SPControlUpload?

### ISSUE THREAD

**Issue by Jckarlos92** [purtuga/SPWidgets#39]
Hi Paul, thanks, no I have an issue: how can I use a list, inside another list as my listName? I mean, I don't want to used "Shared Documents", I want to use "Shared Documents -> MyOwnList" How can I achieve this? Thanks!

**Comment by purtuga** [comment]
I never heard of a list within a list.  Do you mean a folder inside a document library? 
Paul
-- sent from mobile 




On Tue, Feb 24, 2015 at 11:38 AM -0800, "Jckarlos92" <notifications@github.com> wrote:












Hi Paul, thanks, no I have an issue: how can I use a list, inside another list as my listName? I mean, I don't want to used "Shared Documents", I want to use "Shared Documents -> MyOwnList" How can I achieve this? Thanks!

**Comment by Jckarlos92** [comment]
Yeah, exactly, a folder inside a document library. Thanks!

**Comment by purtuga** [comment]
And your trying to use the Upload widget correct?Take a look at the documentation. One of the options on input is the folder where you want the file to be uploaded to. 

Paul
-- sent from mobile 




On Tue, Feb 24, 2015 at 2:49 PM -0800, "Jckarlos92" <notifications@github.com> wrote:












Yeah, exactly, a folder inside a document library. Thanks!

**Comment by Jckarlos92** [comment]
Yeah, I've already looked at it. But all the examples are with the GUID List or with the name List and I think it works at root level. So, how can I make it work on a level that isn't the root one?

For example:

- Main_Folder
  - Sub_Folder

And I want to save my attachments on the Sub_Folder folder

**Comment by purtuga** [comment]
Look at the documentation again. Specifically the `folderPath` input option. 

Paul
-- sent from mobile
