### ISSUE TITLE
pickSPUser: TypeError: jQuery.pt is undefined

### ISSUE THREAD

**Issue by visioinc** [purtuga/SPWidgets#40]
I've noticed that I'm getting this error in the console any time I remove a user from the pickSPUser widget. In firebug, the error links to line 1 of my aspx page, not to jQueryUI or SPWidgets js files.

I'm running jqueryUI (js and css) 1.11.3, jquery 1.11.2, and spwidgets 2.5.0.

This issue is not present on my previous page running spwidgets 2.3 (I believe that is the right version), and changing jquery/jqueryUI versions on either page doesn't seem to affect the error. Changing the new page from spwidgets 2.5.0 to older version does alleviate the problem.

It certainly seems innocent/harmless... as far as I can tell everything is functioning as expected. But I wouldn't mind determining exactly where this is being thrown to be certain.

**Comment by purtuga** [comment]
That should not be happening. I just did a search on the code for that widget and I think the problem is here:
https://github.com/purtuga/SPWidgets/blob/master/src/peoplePickerWidget/peoplePicker.html
Looks like I missed a spot when I refactored the code.  I'll try to get a fix out soon. 

Paul
-- sent from mobile

**Comment by ymihir** [comment]
Hello Paul,
Still I am getting this error. 
![image](https://cloud.githubusercontent.com/assets/7568187/7018246/91fc659c-dd1f-11e4-8cd9-916a760e76bf.png)

**Comment by purtuga** [comment]
Hmmm.  I'll look into it a little later today.   Are you seeing it on the Demo page or on your own project?  I'm thinking it may be the demo page.  I don't think I have built it in a little while.  I'll check. 
If using it on a real project, then make sure you grab the library from the "dist" folder.  It includes the latest and the fix to this issue (or so I believe :) )

Paul
-- sent from mobile

**Comment by ymihir** [comment]
I have used file from dist folder. I am getting issue with Demo page as well as with jquery.SPWidgets.js file.

**Comment by purtuga** [comment]
Thanks for checking.  I'll look into it.  From the screen capture it looks like you are using IE11 - is that right? (I don't think it matters, but just in case)

Paul
-- sent from mobile

**Comment by ymihir** [comment]
Browser version is IE11 only. But SP2010 page is rendering in IE8. Same happening with the Google Chrome also. Browser may not be the issue I guess.

**Comment by rpgramesh** [comment]
Hi,
I am also facing same problem while delete the users.

**Comment by purtuga** [comment]
This is a closed issue.  The latest version should address it.  If you are still having a problem with the latest pleas open a new issue and post details around what your are seeing/experiencing. 

Paul
-- sent from mobile
