### ISSUE TITLE
How can I get the "url" where the file was saved, immediately after it was uploaded?

### ISSUE THREAD

**Issue by Jckarlos92** [purtuga/SPWidgets#41]
Hi Paul! Now, I have another issue: I need to "catch" the URL where the file was saved into, because I need it to save into a list.
How can I achieve this?
Thanks!

**Comment by purtuga** [comment]
Look at the 'onUploadDone' option.  It allows you to define a callback that is executed when the upload is successful. That callback is given an object on input with the file details. Example 1 in the documentation show how to get the URL from the uploaded file. 

Paul
-- sent from mobile

**Comment by purtuga** [comment]
I'm assuming you are good on this one now... Feel free to reopen it if you still need help.
