### ISSUE TITLE
SPWidgets with newer jQuery versions

### ISSUE THREAD

**Issue by Nostalgiaplatz** [purtuga/SPWidgets#44]
This is an amazing toolset so thanks so much!

I have used primarily the people picker up until now and had success. I recently however went to build it into a page I am working on built on top of the bootstrap framework (v3) and as that requires Jquery 1.9.1 at least I found that the results display doesnt seem to work/display. Stripping everything out (no bootstrap or anything) I found that it was changing the jQuery version to a lower version that enabled this to function.

Do you plan to release an update to support jQuery 1.9.1 + at any time?

Thanks!

**Comment by Nostalgiaplatz** [comment]
So I just tested with JQuery 1.10.2 as noticed in your demo page you used that version and it is working correctly! Strange that it doesn't work with JQuery 1.9.1

**Comment by purtuga** [comment]
Thanks.  Glad they have been working out for you. That version of jQuery (1.9.1) has a bug that affects the API calls being done by these widgets.  See this blog post:  http://sympmarc.com/2013/02/05/spservices-compatibility-issues-with-jquery-1-9-1/
Paul
-- sent from mobile
