### ISSUE TITLE
Trouble using SPWidgets - Upload

### ISSUE THREAD

**Issue by seroche** [purtuga/SPWidgets#48]
Hi,

I'm using SP2010 - SP2 with IE11 (IE8 - Mode). When I use your control with the default settings I will get a 404 error because it can't find the page UploadEx.aspx. 

![image](https://cloud.githubusercontent.com/assets/12636347/8373028/65a47b2a-1c1b-11e5-98f9-164df7d1e8f2.png)

Code:
    <div id="upload" style="height: 500px;width: 300px;">

    </div>

    $("#upload").SPControlUpload({
        listName: "Shared Documents"
    });

I tried to workaround this problem by modifying the UploadPage option... Once that done my upload_div shows the full sharepoint upload page (and not a fancy control).

![image](https://cloud.githubusercontent.com/assets/12636347/8373093/feeac71c-1c1b-11e5-8806-5792d856871c.png)

    $("#upload").SPControlUpload({
        listName: "Shared Documents",
        uploadPage: "/_layouts/Upload.aspx"
    });

Is your control compatible with SP2010 + Ie8? 

Am I missing something?

Thank you,
Sebastien

**Comment by purtuga** [comment]
Hi Sebatien. 
I have not touched this widget in a long time, but at the time that I created it, it was working on both Sharepoint 2007 and 2010. I seem to remember another user reporting an issue recently with it not finding the upload page.  

Your setup looks good to me.  Did you see any errors in the console? If you upload the Demo page to your Sharepoint site and try the upload demo on it, does it work?

Also: what version of SPwidget and JQuery are you using?  And if you get a chance, can you try this with Chrome or Firefox, just to see if it is browser related?
