### ISSUE TITLE
Display Email Address in People Picker instead of Display Name

### ISSUE THREAD

**Issue by SamSlaught** [purtuga/SPWidgets#50]
I am running into an issue with this plugin. I do a lot of SharePoint project for big clients such as P&G and Kroger. At big companies like this, a lot of people have the same name (Ex. I type in "Bob Smith", I will have multiple SharePoint accounts returned with the name "Bob Smith"). How is a user suppose to know which is the correct account to choose?

It is possible to switch out the Display Name with the user's email address when searching the people picker?

**Comment by purtuga** [comment]
Yes, there is a way, although its not very well document - until now. 
You can use the `filterSuggestions` input option to loop through the list of suggestions that will be presented and alter the `label` attribute. 
Look at the example I just pushed through in the documentation for this options - here: https://github.com/purtuga/SPWidgets/blob/master/documentation/SPWidgets.pickSPUser.md

Let me know if this helps.

**Comment by SamSlaught** [comment]
Thanks Paul! Wow, works great! Two quick things I wanted to let you know:

1) The example you have in the documentation for "filterSuggestions" didn't work for me. Nothing would show up in the dropdown. What I had to was push each "userInfo" object into the "newSuggestions" array. You might want to update your documentation example to this:

```javascript
options.filterSuggestions = function (suggestions) {
    var newSuggestions = [];

    $.each(suggestions, function (i, userInfo) {
        // If the user's ID is not -1, then add them return it.
        if (userInfo.accountId !== "-1") {
            // Change the visible label to include email
            userInfo.label = userInfo.label + " (" + userInfo.email + ")";
            newSuggestions.push(userInfo);
        }
    });

    return newSuggestions;
}
```

2) This might be a bug. I have the people picker returning SharePoint groups along with users. However, when I look at the "accountType" part in the "userInfo" object for one of those groups, it still says "User" in it. Shouldn't it be "SharePointGroup"? Also, in the "email" part for a group in the "userInfo" object, it was returning a random SharePoint user's email address. Weird. [Ex. MySharePointGroup (mike@thisdomain.com)]


Thanks again for all your help. I love this plugin; you've done a great job on it.

**Comment by purtuga** [comment]
Glad you got it working... and sorry about the bad code in the example... that's what I get when I rush that out... I just corrected it..

**Re: accountType of User for groups**
I just looked at [the code](https://github.com/purtuga/SPWidgets/blob/master/src/peoplePickerWidget/peoplePicker.js#L399) and I don't do any processing on that value...I simply copy it from the XML response that was received from the server.  
Could you look at the XML response in the browser developer tools (chrome works best) to see what the server is returning?

**Comment by marktiderman** [comment]
Thanks Paul.  Great stuff.  Good work Sam.

**Comment by SamSlaught** [comment]
Hey Paul! Sorry it took me a while to get back, been super busy. Here is the SOAP XML returned from the people picker. It might some kind of issue with our server and it's not that big of a deal if it can't be easily figured out. (Ex. **CAEX\global_owner** is a group, not a user)

```xml
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><SearchPrincipalsResponse xmlns="http://schemas.microsoft.com/sharepoint/soap/"><SearchPrincipalsResult><PrincipalInfo><AccountName>CAEX\cody549</AccountName><UserInfoID>81</UserInfoID><DisplayName>Cody Moorefield</DisplayName><Email>cody@streamlinedstudio.com</Email><IsResolved>true</IsResolved><PrincipalType>User</PrincipalType></PrincipalInfo><PrincipalInfo><AccountName>CAEX\global_owner</AccountName><UserInfoID>96</UserInfoID><DisplayName>Global_Owner</DisplayName><Email>cody@streamlinedstudio.com</Email><IsResolved>true</IsResolved><PrincipalType>User</PrincipalType></PrincipalInfo><PrincipalInfo><AccountName>CAEX\qa_read</AccountName><UserInfoID>94</UserInfoID><DisplayName>QA_Read</DisplayName><Email>cody@streamlinedstudio.com</Email><IsResolved>true</IsResolved><PrincipalType>User</PrincipalType></PrincipalInfo><PrincipalInfo><AccountName>CAEX\qa_write</AccountName><UserInfoID>95</UserInfoID><DisplayName>QA_Write</DisplayName><Email>cody@streamlinedstudio.com</Email><IsResolved>true</IsResolved><PrincipalType>User</PrincipalType></PrincipalInfo><PrincipalInfo><AccountName>CAEX\reqester</AccountName><UserInfoID>93</UserInfoID><DisplayName>Requester</DisplayName><Email>cody@streamlinedstudio.com</Email><IsResolved>true</IsResolved><PrincipalType>User</PrincipalType></PrincipalInfo></SearchPrincipalsResult></SearchPrincipalsResponse></soap:Body></soap:Envelope>
```

**Comment by purtuga** [comment]
np. THanks for posting back.
So yes, this looks to be a miss-configuration on the server somewhere... If you look at your entry above, its coming back with a PrincipalType of "User"...

**Comment by SamSlaught** [comment]
Ok, no worries. Thanks for all your help and for one awesome plugin!

**Comment by shankarnss** [comment]
Hi Paul,

It is a very nice article and you have done excellent Job. I am currently interested in the people picker control. I copied the whole demo with src into SharePoint site pages library and People picker works wonderful. Is there a simple example of People picker with just an input control and reference to libraries?

I was unsuccessful in implementing using one of your links (https://github.com/purtuga/SPWidgets/tree/master/src/peoplePickerWidget) with code as follows -

What am i missing?

With regards,
Shankar

**Comment by purtuga** [comment]
Hi Shankar. 
Sounds like your question is unrelated to this item. Could you please open up a new issue for it? 
Also: ensure you include your code - it did not get saved in your post post above. 
Thanks.

**Comment by shankarnss** [comment]
Hi Paul,

I did open a new issue. Kindly help me sir.

With regards,
Shankar

**Comment by shankarnss** [comment]
Hi Paul,

My issue number is #51.

With regards,
Shankar

**Comment by shankarnss** [comment]
Dear Paul,

I was looking at SP Widgets and the tool is awesome. I was able to do a
test implementation and it was easy and successful.

I was trying to achieve few modifications:
1) Replicate the upload button click in a custom button. Is it possible? if
yes could you please give me some pointers.

2) Encountered an issue: Sometimes the upload/busy wheel keeps spinning and
I do not see any messages. I think some function/script is running
infinitely. How do i pin point it?

3) Exception handling: I found the events '1' No File uploaded, Upload form
is ready for user input.  '2' No File uploaded. User has defined.. & '3' File
has been uploaded. what is the difference between 1 & 2?
How do i handle other exceptions? is there anything defined?

Really appreciate your help on this.

With regards,
Shankar

**Comment by purtuga** [comment]
Hi Shankar,
Your questions do not seem to be associated with this old post.  Can you open a new issue dedicated to the trouble you are having instead?
Thank you.

Paul

-- sent from mobile
