### ISSUE TITLE
SPFilterPanel person column

### ISSUE THREAD

**Issue by thermador64** [purtuga/SPWidgets#52]
I am using the SPFilterPanel and it works great except for one thing. When I have a person column and the person has an apostrophe in their last name (like O'Brein) I can not select the user name.  Any help with this issue is appreciated.

**Comment by purtuga** [comment]
@thermador64 
Sorry for the trouble... I will look into this... I think the problem is with the People Picker widget, which I noticed the other day on an app I have where it was being used. The person's name there was O'maly. 

I'll get back to you on this...

**Comment by purtuga** [comment]
@thermador64,
Could you tell me the following:

1.  When you say you can't select them, you mean in the auto-complete suggestion poupup, correct?
2.  Do you see any errors on the browser console?
3.  What version of SPWidgets, jQuery and jQuery UI are you using?

I just did a quick test and although I thought it was going to be easy to recreate it, I'm not seeing the problem... but I'll keep trying (later)
Thanks in advance.

**Comment by thermador64** [comment]
I do mean in the auto-complete suggestion popup. In the web browser I get the error: Syntax error, unrecognized expression: div[data-pickspuserid='-1'][data-pickspusername='O'Brien, Amanda D'] which occurs in jquery.SPWidgets.patch. I am using jquery-1.11, SPWidgets v2.5.0, with the patch and the B4 modification patch.

**Comment by purtuga** [comment]
This defenetely helps. Thanks.  Looks like it's a selector issue I have to fix. 

Paul
-- sent from mobile

**Comment by purtuga** [comment]
@thermador64 I was able to recreate this problem and pushed through a fix to the Master branch... Can you download the library from the [Dist](https://github.com/purtuga/SPWidgets/tree/master/dist) folder and try again. 

**Note**: The Master branch is currently under heavy refactoring and you might find that it will not work in your env. - especially if using SP2010 with IE (since SP tells IE to render the site in IE8 mode)... if that is the case, let me know and I'll add this fix to v2.5.0 branch and issue a new patch.

**Comment by thermador64** [comment]
I will do that when I get back in the office on Monday. Thanks for the quick response.

**Comment by thermador64** [comment]
I tried out the fix, and it works on the dev server. Unfortunately, on our production server I get 'Object expected' error at line 438 of jquery.SPWidgets.js and the SPFilterPanels are not created.

**Comment by purtuga** [comment]
Ok.  I'll have to branch at the point where v2.5.2 was created and add these fixes there, then cut a new version.  
Just curious why it worked in Dev. Are you using same version of SP and browser type in both environments?
(Ps. I would have expected errors from IE <10)

Paul
-- sent from mobile

**Comment by thermador64** [comment]
The browser is the same and the same version of SP is being used, but the settings on the servers are different.  If I had to guess I would say the prod server is set to make the browser to run in enterprise mode and the dev server is not, is what the issue is.

**Comment by thermador64** [comment]
I made the fix in the version I am using.  The two place's data-pickspusername occurs I replaced ' with "

**Comment by purtuga** [comment]
Hi @thermador64

Sorry I have not had a chance to create a patch. I'll try this weekend. 
Your post above stripped out the changes you made.  But if you looked at the diff reference above, then you should have a good idea of what I did.
