### ISSUE TITLE
Help on FileUpload control

### ISSUE THREAD

**Issue by shankarnss** [purtuga/SPWidgets#53]
Hi Paul,

I am very happy with the People picker control. I was trying to use FileUpload control and have not been successful. My code is very simple and what am i missing? HTML code is getting blocked.

Details of my code are 
1) references to Jquery.min, jquery-ui.min.js, spwidgets.js and spservices.
2) have a simple div tag with id and class = file_upload
3) On page load i have the function 
$("div.file_upload").SPControlUpload({ listName: "Shared Documents" })

My page is blank. I don't understand what am i missing? 

With regards,
Shankar

**Comment by shankarnss** [comment]
Hi Paul,

I am very happy with the People picker control. I was trying to use FileUpload control and have not been successful. My code is very simple and what am i missing?

**Comment by purtuga** [comment]
@shankarnss 
A few questions:

1. Any errors in the console?
2. What version of SPWidgets are you using?
3. What version of SharePoint?

_Also, see the github instructions on how to insert blocks of code - https://guides.github.com/features/mastering-markdown/ - specifically, the section on syntax highlighting. It highlights how you can wrapp code in 3 back-ticks if wanting to post it here_

**Comment by shankarnss** [comment]
Hi Paul,

1> I am able to get the file upload working.
2> The latest version of SPWdigets which i downloaded from github (https://github.com/purtuga/SPWidgets).
3> SharePoint 2010. 

I need some changes here. Here are some more questions

1) I want to simulate the upload function on click of a save button on my form,  Is it possible? 
2) There is not option to delete an uploaded file. How do we achieve that?

With regards,
Shankar

**Comment by purtuga** [comment]
Hi Shankar. 
Re: your questions above
1) no, there is no way to way to that in this widget.  I guess you could try to grab the upload button, hid it and the emit a click() event on it from your save button logic.  Maybe that will work. 

2) this widget is not meant to delete files. You need to look at the List API and the updateListItems method.  

3) not sure I understand.  The widget only uploads one file at a time.  Do you mean only allow it to upload once? If so, not its not supported but you can code it by bidding the widget after the first successful  file upload. 

4) no, currently there is no way to restrict what type of files are selected. 

Paul
-- sent from mobile

**Comment by shankarnss** [comment]
Thanks Paul,

I was able to achieve all my functionality using jquery. Thanks for your timely response. 

Very useful tool. 
--Shankar
