### ISSUE TITLE
Timeout for SharePoint Filter Panel

### ISSUE THREAD

**Issue by thermador64** [purtuga/SPWidgets#54]
Occasionally when clicking on the filter button of a Filter Panel a timeout occurs. I was wondering how you would increase the length of time between timeouts?

**Comment by purtuga** [comment]
I'm not sure what you mean by timeout.  The widget itself does not have a timeout... When the Filter button is clicked, it collects the data the user entered and then executes your callback.  
Can you explain more about whats happening and what timeout you are referring to?

Paul
-- sent from mobile

**Comment by thermador64** [comment]
Sorry, upon further investigation the issue is with SharePoint not the SPFilterPanel.  SharePoint has a security validation that times out after 30 minutes.
