### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by ANURROY** [purtuga/SPWidgets#56]
I got issue in below line can you please help

function setPeoplePicker(){
$("#bumgr").find("input").pickSPUser();
}

Cannot read property 'SPGetCurrentSite' of undefined SPWIDGETS.JS

Thanks and Best Regards,
Anurag

**Comment by purtuga** [comment]
The code in your example does not look like valid jQuery calls - but maybe that was only a mistake while pasting your code here.  
A few questions:
-  What version of SPWidgets are you using?  -  what version of jQuery?-  what version of jQuery UI?-  can you post the code of how the libraries (jQuery, jQuery UI and SPWidgets) are being loaded?-  in the developers tools, under the Network tab, are there any errors in trying to load the 3 libraries?

Some information on getting started here: http://purtuga.github.io/SPWidgets/Look at the usage section. 

Paul
-- sent from mobile

**Comment by ANURROY** [comment]
Hello Sir,
Can you please let me know the correct version

**Comment by purtuga** [comment]
For SPWidgets the latest is 2.5.3 - it's listed on the projects web page: http://purtuga.github.io/SPWidgets/
For jQuery and JQuery UI, take the latest version at the 1.x level. 

Paul
-- sent from mobile
