### ISSUE TITLE
XMLHTTPRequest issue from demo page

### ISSUE THREAD

**Issue by jackjamieson** [purtuga/SPWidgets#57]
I uploaded the Demo.SPWidgets.aspx to a library on my machine but it cannot access anything.  In Chrome the dev tools show an error on POST even as soon as the page loads from _vti_bin/SiteData.asmx.

I believe the error is coming from the fact that the script removed the colon from the port on my site.  The POST is trying to reach http://my-site37509/sites/1/_vti_bin/SiteData.asmx when there should be a colon before the port like http://my-site:37509/sites/1/_vti_bin/SiteData.asmx.

**Comment by purtuga** [comment]
What version are you using? 
(I thought I fixed this issue)

**Comment by purtuga** [comment]
So I just noticed that the Demo file (under the Demo folder) has not been updated in close to 1 year. Found that I had bug in the build, which I just fixed  73e8f5c05b0b

Can you download it again and try?

https://raw.githubusercontent.com/purtuga/SPWidgets/master/demo/Demo.SPWidgets.aspx

**Comment by jackjamieson** [comment]
I was using 2.5.3, but https://github.com/purtuga/SPWidgets/commit/73e8f5c05b0b589868a65d28cc787278e315c5c2 seems to have fixed it.  Thanks for the quick response!

**Comment by purtuga** [comment]
Np @jackjamieson ... Sorry for the trouble and for reporting it... I have fixed the build so this should be corrected going forward as I make other changes.
