### ISSUE TITLE
SPWidgets file upload issue on Internet Explorer 11 

### ISSUE THREAD

**Issue by awube12** [purtuga/SPWidgets#58]
Hello Paul, I was wandering if you assist us resolving this issue. The SPWidgets file upload functionality used to work successfully in previous version of ie. After we upgraded to ie11, part of its functionality stopped working. The file gets uploaded. It is just updating the properties of the file. It looks like the issue is with the line ev.page.find('input[title="test"]').val(3). This line doesn't run. Here is the code for the upload functionality.

function openpage() {
	$('#upload').SPControlUpload({
		listName:       "XXXX",
		onUploadDone:    null,
		checkInFormHeight:'50em',
		overwrite:		 false,
		onPageChange:    function(ev){														
		if (ev.state == 3 && ev.isUploadDone) {
			//alert("Upload Done!");													
			ev.hideOverlay = false;		  
		} else if (ev.state == 3 && !ev.isUploadDone) {
			ev.hideOverlay = false;			
			setTimeout(function(){				
			ev.page.find("input[title='test']").val(6);               
				// Find the "Save" button and .click() it
					ev.page.find("input[type='button'][name$='SaveItem']:first").click();
					}, 100);
				}
			}//end: onPageChange()
		});     
}

Please let us know if you have any questions please.

Thank you!

**Comment by purtuga** [comment]
Is it that the line of code does not run (meaning the 'if' condition is never met) or that it runs but can't find your input element?
Put in a few console.log statements to get more information if the onPageChange callback is being called and output the value in the ev.state. 
It that line of code is being executed but does not find your input field, then I suggest you put in a breakpoint in the development tools and inspect the content of ev.page for the element you need. 

Paul
-- sent from mobile

**Comment by awube12** [comment]
Thank you Paul. I figured it out. The issue was with the version of the jquery file. Somehow the functionality works only in version 1.12.1. in our environment. 

Thanks again for prompt response!

**Comment by purtuga** [comment]
Glad you figured it out.  What version of jQuery where you using before?

Paul
-- sent from mobile

**Comment by awube12** [comment]
We were using version 1.10.2. We tried it with the latest versions of 2.2.1 & 2.1.0. It didn’t work. It also didn’t work with prior versions of 1.10.2. It is still strange because it only works with version 1.12.1.

 

Thanks!

**Comment by purtuga** [comment]
Hmm. Thanks for posting back. That is strange.  V2.x is not advisable in SharePoint because that version only supports modern browsers and SharePoint (under IE) will tell the browser to render the page with an old version (SP2010 says use ie10.  SP2010 says use IE8!!)
But the others at 1.x level should have worked.  
Oh well. You found a solution. That's good. :)
Paul
-- sent from mobile
