### ISSUE TITLE
Lookup with Descending sort help super please

### ISSUE THREAD

**Issue by EnlightenMePlease** [purtuga/SPWidgets#59]
Hi there,
I've tried for most of the day to get this to work with many variations, but just a total noob at this and can't get the configuration right. I have added jquery items to pages before though.
I'm really hoping you can help me out with what "seems" to be a pretty simple thing to do.
- Using jquery 1.11.3 and jquery ui 1.11.4 hosted in the SiteAssets library
- SPF2013
- I have a lookup field that I just want to sort descending - that's it !!
- no text typing, just pure lookup - click and select from the dropdown
- no multiple values permitted
- column of lookup is MEETING
- list "friendly name" is MEETING ATTENDEES
- list "URL name" is MEETPEOPLE

Many Many thanks in advance!
EMP

**Comment by purtuga** [comment]
HI...
You really should post these types of jQuery/javascript question to stack-overflow...they do a much better job helping others than I do.

If the lookup is a pure HTML `select` element, then following should do it:
```
var meetingField = $("[title='Task Status']");
var meetingOptions = meetingField.find("> option");

meetingOptions.sort(function(a, b){
    if (a.textContent < b.textContent) {
        return 1
    }
    if (a.textContent > b.textContent) {
        return -1
    } 
    return 0
});

meetingField.empty().append(meetingOptions);
```

Hope this helps... 

/Paul

**Comment by EnlightenMePlease** [comment]
Hi Paul,
Thanks so much for helping. I will continue with StackOverflow if you say so, but hope I can convince you to have another look if you're willing? I added the jQuery and javascript references, but the code doesn't seem to work. I also tried changing the meetingField of 'Task Status' to 'Meeting', assuming this is where I link the code to the proper column.
No errors appeared in F12 Dev Tools in Chrome either.
The lookup is a calculated column that combines (in text) date information and the description (if this matters).

Thanks again,
Ken

![meeting lookup](https://cloud.githubusercontent.com/assets/18219287/14224366/fb51c5c6-f855-11e5-919a-eb5bfbe9af16.png)

**Comment by purtuga** [comment]
I  would like to see the HTML markup for the select element and its options. Can you right-click the Select element and choose "inspect element" and then post a screen capture of the HTML markup?

Paul
-- sent from mobile

**Comment by EnlightenMePlease** [comment]
Truly appreciate this Paul!
Hopefully I captured the info you needed, just let me know if more is required.
Thanks again,
Ken

![inspect element](https://cloud.githubusercontent.com/assets/18219287/14227031/43eb5b58-f8b0-11e5-860f-8fa33be47e71.png)

**Comment by purtuga** [comment]
Ok... i see the issue... This is a required field and the title attribute contains that value in it... try this:

```
var meetingField = $("[title='Meeting Required Field']");
var meetingOptions = meetingField.find("> option");

meetingOptions.sort(function(a, b){
    if (a.textContent < b.textContent) {
        return 1
    }
    if (a.textContent > b.textContent) {
        return -1
    } 
    return 0
});

meetingField.empty().append(meetingOptions);
```
/paul

**Comment by EnlightenMePlease** [comment]
Hi Paul - not having much luck. I've added all the code here b/c maybe I'm just doing something silly.
- no codes appear
- tried removing the requirement of the field (in List Settings) and correspondingly removed the "Required Field" from the title
- tried jquery 1.12.2 (currently using 1.11.3) as well as the full .js instead of the .min.js
- tried replacing the spaces in the Title with (underscore)x0020(underscore)

Thanks again Paul,
Ken

```
<script type="text/javascript" src="/pm/project/SiteAssets/Scripts/jquery-1.11.3.min.js"></script>
<script type="text/javascript">

var meetingField = $("[title='Meeting Required Field']");
var meetingOptions = meetingField.find("> option");

meetingOptions.sort(function(a, b){
    if (a.textContent < b.textContent) {
        return 1
    }
    if (a.textContent > b.textContent) {
        return -1
    } 
    return 0
});

meetingField.empty().append(meetingOptions);
</script>​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​
```

**Comment by EnlightenMePlease** [comment]
sorry - by no codes I meant no errors :)

**Comment by purtuga** [comment]
I'm running out of ideas here... You will need to dig in and likely debug with break points... if you don't know how to set those, here is a version of it with "alerts()" to report a few things... 

```javascript
<script type="text/javascript" src="/pm/project/SiteAssets/Scripts/jquery-1.11.3.min.js"></script>
<script type="text/javascript">

    (function($){
        
        alert("jquery version: " + $.fn.jquery);
    
        var meetingField = $("[title='Meeting Required Field']");
        
        alert("Found meeting field? = " + (meetingField.length ? "YES" : "NO"));
        
        var meetingOptions = meetingField.find("> option");
        
        alert("Number of options under Meeting field = " + meetingOptions.length);

        meetingOptions.sort(function(a, b){
            if (a.textContent < b.textContent) {
                return 1
            }
            if (a.textContent > b.textContent) {
                return -1
            } 
            return 0
        });

        meetingField.empty().append(meetingOptions);
    
    }(jQuery));
    
</script>
```

/Paul

**Comment by EnlightenMePlease** [comment]
Appreciate everything, Paul.
Couldn't get it debugged unfortunately due to my lack of knowledge. But your alerts worked perfectly - couldn't find the field and showed 0 options.

With much more tweaking, especially now knowing about the "Required Field" suffix on the Title, I was able to get Marc's SPServices SPFilterDropdown working for this - with a couple wrinkles. So I'll be posting something on his Discussion. Works out anyway because I also needed (and got working) a couple cascading dropdowns using his CascadingDropdown.

Thanks again for your help,
Ken
