### ISSUE TITLE
pickSPUser

### ISSUE THREAD

**Issue by thermador64** [purtuga/SPWidgets#60]
I am trying to filter the users by domain with the pickSPUser, and I have included my code. 
![code](https://cloud.githubusercontent.com/assets/15127850/14892568/64fcffe8-0d39-11e6-8e69-2bfce01c6a4c.JPG)

I am using the column `Name` because if you get the UserInfo list this column has the `domain\id` information. I don't know if you are using a different list, or if I am just doing something wrong. Any help would be appreciated.

**Comment by purtuga** [comment]
That does not look like a supported way to call  this widget.  Please read the API documentation here: https://github.com/purtuga/SPWidgets/blob/master/documentation/SPWidgets.pickSPUser.md
This widget does not query the user list directly.  It uses searchPrincipals SharePoint API.  You might be able to achieve goal by using the widget's 'filterSuggestions' option. 

Paul
-- sent from mobile

**Comment by thermador64** [comment]
Thanks for the tip. I was able to get it working with the filterSuggestions option.

**Comment by purtuga** [comment]
Glad to hear that.
