### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pickSPUser' of undefined  onclick

### ISSUE THREAD

**Issue by nishant12** [purtuga/SPWidgets#61]
$("input[name='users']").pickSPUser({
    allowMultiples: false
});

$("input[name='user']").pickSPUser("method", "clear");
$("input[name='user']").pickSPUser("method", "destroy");

$("input[name='user']").pickSPUser("method", "add", value);
value is in the format ('4;#John Smith')

The above code is written inside of the jQuery UI Dialog, it popups on the click of edit link, so I have to clear and destroy the field every time the user clicks on the edit dialog.

Everything works fine but when I click on the cross mark to remove the User, this error logs in the console
Uncaught TypeError: Cannot read property 'pickSPUser' of undefined  onclick	@	form.aspx

Please can you help me with this issue. I am not able to understand what could be causing this issue.

Thanks.

**Comment by purtuga** [comment]
This was reported to me a few months ago and I thought I fixed it.  What version are you running?

Paul
-- sent from mobile

**Comment by nishant12** [comment]
Version 2.5.1 

Thanks,
Nishant

-----Original Message-----

**Comment by purtuga** [comment]
Please upgrade to v2.5.3 (latest)... Both v2.5.2 and 2.5.3 had fixes to People Picker.. It think the issue you are encountering was fixed in [v2.5.2](https://github.com/purtuga/SPWidgets/releases/tag/v2.5.2).

**Comment by nishant12** [comment]
Yeah it works now. Thank you so much for your Prompt response. 

But now date picker works like a pickSPUser widget. I mean when I select a date it add on to the top with a cross mark, earlier it was populating in the Input field. Can you please suggest something how to change that?

**Comment by purtuga** [comment]
No Problem.

Are you opening a new issue for the date picker widget issue? Check to ensure you have "allowMultiples" set to false.

**Comment by nishant12** [comment]
Do you want me to open a new issue?

Initially allowMultiples = false, but later when it comes to this function dateField = function dateField(containers, options), in options, allowMultiples is set to true, not able to figure out where to set it to false. Where are the options set?

I had more question about SPUser, in People.getUserHtmlElement(o, id, user), if I pass one more parameter 'email' so that it adds to the selected element, will it affect the functionality of the user. As I need the email id of the user selected. 
Is there a way to retrieve the email id of the user using SPUser widget ?

Please can you help me out.
Thanks.

**Comment by purtuga** [comment]
Yes, for the Date Picker widget, please open a new issue (for my own sanity :) )

I'm going to checkout the demo app to see if this is happening there...

For your DatePicker questions:

### re: is there a way to get the email of the user

I think the event `spwidget:peoplePickerAdd` will give you that... Your listener will get 3 input params... the 3rd is the person Object which I think contains the email attribute that is returned by the searchPrincipals API... 

### re: changing the display HTML in People.getUserHtmlElement

I don't think so... just don't change the existing css class names and I think it should still work. 

/paul.

**Comment by nishant12** [comment]
Apologies for such a late reply, had been very busy lately. 

There was no issue with date picker widget, it was initialising with allowmultiples:true. It's working fine.
I got the email of the user with spwidget:peoplePickerAdd event. 

Thank you so much for the Plugin. Great work.

**Comment by purtuga** [comment]
No problem.  Thanks for responding. 

Paul
-- sent from mobile
