### ISSUE TITLE
programmatically set default user

### ISSUE THREAD

**Issue by netsuper** [purtuga/SPWidgets#62]
Is there a way to add an SPuser to the peoplepicker as a default?  I am retrieving an item from a SPlist including a person type and want to "put" that persontype field into the pickSPUser as the default?

Hope that makes sense...
Scott

**Comment by purtuga** [comment]
Hi.Yes that is possible.  Use the 'add' method documented under the Methods section for this widget:
https://github.com/purtuga/SPWidgets/blob/master/documentation/SPWidgets.pickSPUser.md
There is an example usage there as well. 
Paul
-- sent from mobile

**Comment by netsuper** [comment]
Thanks, I had tried that before, but this time it worked?!

**Comment by purtuga** [comment]
Cool. Glad it worked.
