### ISSUE TITLE
Filename to long error not showing

### ISSUE THREAD

**Issue by psubrownie** [purtuga/SPWidgets#65]
I ran into an issue when uploading a file with a name longer than 128 characters.  The upload looks like its happening and then the widget just resets its state.  Debugging I realized you actually do handle this, so I thought something was wrong with my onPageChange but its based on the example.
I found `opt.$errorCntr.animate({ opacity: 1 }, 5000, function () {
              opt.clearError(); 
            });
opt.clearError = function () {
          opt.$errorCntr.css('display', 'none');
          return opt;
        };
`  which appears to hide the error message (clearError) as soon as its done fading in.
Can anyone else confirm this by uploading a file longer than 128 characters in name.

**Comment by purtuga** [comment]
I'll try to recreate this later when I get home.  What version of the library are you using?

Paul
-- sent from mobile

**Comment by purtuga** [comment]
I just tested this and it worked for me using the Demo page provided in the demo folder of this repo. (latest version - v2.5.2).  My file name was 137chr. and I was using SP2010. 

Can you use the demo page ([Demo.SPWidgets.aspx](https://raw.githubusercontent.com/purtuga/SPWidgets/master/demo/Demo.SPWidgets.aspx)) and test it out on your side?  
Do a "Save As" on the link above and save the aspx file to your pc... then upload it to SP.

**Comment by psubrownie** [comment]
Seeing how it works in the demo, I think my issue is that I have the upload in a popup that isn't expanding to show the error. and I just see the file chooser come back.  I'll make my modal bigger hardcoded.  I misinterpreted the jQuery easing and didn't realize it waited 5 seconds and then removed the dialog.  I thought it was a 5 second fade or something.
Thanks for your work on this project, its a great help.

**Comment by purtuga** [comment]
Glad to hear that.  Note the I will be deprecating this widget in the next major version.  This upload widget is really a 'screen scrapper' of the upload page and was initially developed for SP2007.  I might introduce a new widget to replace it. 

Paul
-- sent from mobile
