### ISSUE TITLE
Can these widgets work on a HTML Page?

### ISSUE THREAD

**Issue by andresan21** [purtuga/SPWidgets#69]
Hello,
Can the People Picker work on a Non ASPX page? I was trying to make it work on a HTML page and I can't get it to work. Currently I am using a media content and pointing to a HTML page for new submissions and I am trying to make the people picker work on this page.

**Comment by purtuga** [comment]
I don't think it will, but I never really attempted it... The current version has some dependencies on global variables that are only available when the SharePoint JavaScript are loaded (I think only getSiteUrl.js).. 

Good news is that the next version of SPWidgets will support such cases... An alpha/beta version will be coming soon.
