### ISSUE TITLE
SPControlUpload Widget doubt about Content Types

### ISSUE THREAD

**Issue by EGLimon** [purtuga/SPWidgets#70]
Hi, my question is, is there a way to avoid the pop up with Content type properties(i cant delete it) that comes after the document is attached, my problem is that the event onUploadDone never reach i cant continue with my process.

if you could give any advice that would be great.

![ctype](https://cloud.githubusercontent.com/assets/23127388/19862683/f6da862e-9f56-11e6-85ce-3dbdccf15640.PNG)

**Comment by purtuga** [comment]
Yes, there is a way to avoid the popup...
Take a look at my response here to #68: https://github.com/purtuga/SPWidgets/issues/68

/Paul

**Comment by EGLimon** [comment]
Thank you it was really helpful. now i run my code checking the state and action.
