### ISSUE TITLE
SPControlUpload - Permission Denied

### ISSUE THREAD

**Issue by jeff-brooks** [purtuga/SPWidgets#72]
I'm using SharePoint 2010 with IE 11.

I have a document library that opens the Editform.aspx dialog after uploading a document into the library.

I'm trying to use SPControlUpload to upload a file into the library from elsewhere. It appears that the file is being uploaded, however javascript is complaining about permission denied and the editform.aspx is never displayed in the widget. 

The single page demo is able to bring up the editform, and does not throw any permission denied javascript errors.

Here are screenshots of the javascript error and network activity:
![image](https://cloud.githubusercontent.com/assets/24594636/21242079/990cb5c8-c2e0-11e6-8d9e-074778207272.png)

![image](https://cloud.githubusercontent.com/assets/24594636/21242132/d66fe7aa-c2e0-11e6-8151-602c46140a66.png)

**Comment by purtuga** [comment]
Your page that is "elsewhere" and that contains the code that uses SPControlsUpload - is that page hosted in the same SharePoint site to where you are uploading the file?  

I see above that it looks like your code is running in a file called "AddPQItem.html"... My guess is that is not going to work.... This library depends upon a few files/functionality that is normally loaded with regular SharePoint pages...  You probably need to create a SharePoint webpart page, and then add a content script web part to it that loads your code.

/Paul.

**Comment by jeff-brooks** [comment]
Thanks for the response Paul. I'll look into that option.

In the meantime, yes, you are correct - in this case SPControlsUpload is being called from an html page. That html page is hosted within the same site as the document library I'm trying to upload to. The html page is uploaded into a different library on the same site.

**Comment by purtuga** [comment]
Then I'm pretty sure that is the problem - the plain HTML file will not work. One quick way might be for you to use the aspx file I use to create the demo showcase app. The file is here:
https://github.com/purtuga/SPWidgets/blob/master/demo/src/Demo.SPWidgets.aspx
You will have to remove some code from it and insert yours. 
Good luck. 
Paul

-- sent from mobile

**Comment by jeff-brooks** [comment]
OK - thanks again Paul.

**Comment by jeff-brooks** [comment]
So I modified the HTML file just enough to plop it in a CEWP on a web part page and tried again. I'm seeing the same behavior there: 
- the file does upload, but the editform never appears
- javascript error of permission denied
- the widget appears as if it is still trying to upload

![image](https://cloud.githubusercontent.com/assets/24594636/21264240/30d0ba48-c369-11e6-8acd-2ee4d4b8c9df.png)

![image](https://cloud.githubusercontent.com/assets/24594636/21264224/17c04abe-c369-11e6-86fc-8e38fce8fd80.png)

![image](https://cloud.githubusercontent.com/assets/24594636/21264255/4a39fb02-c369-11e6-8a32-b67417b81d45.png)

my code was by and large taken from different examples. 
`$('#SPControlUpload').SPControlUpload({
					listName: 'Documents',
					overwrite:      true,
					//uploadPage: '/_layouts/Upload.aspx', //doesnt seem to help
					overlayMessage: "Working...",
					onUploadDone: function (file){
						alert("File upload done. File url: " + file.EncodedAbsUrl);
					},
					onPageChange: function(ev){
						// If we're done with the upload, then continue to show the
						// overlay, and fade out the area that contained the upload control.
						if (ev.state == 3 && ev.isUploadDone) {
							ev.hideOverlay = false;
							setTimeout(function(){
									$(this).dialog("close").dialog("destroy");
									alert("Upload Done!");
								}, 1000);

						// If file was uploaded, but we have required fields to fill out,
						// then adjust page to only show the required data...
						} else if (ev.state == 3 && !ev.isUploadDone) {

							// Because we're coming from the same domain, we
							// have full access to the content of the page,
							// and thus we can manipulate it. In this example
							// I hide all chrome and show only the form fields
							// the user should be filling in.
							// Note that this works because in this very simple
							// example, I assume that the required fields form
							// does not have any special fields, like people pickers,
							// etc.
							ev.page.find("form")
								.children(":visible")
									.css("display", "none")
									.addClass("ptWasVisible")
									.end()
								.find("input[title='Name']")
									.closest("div[id^='WebPart']")
										.appendTo(ev.page.find("form"));
								}

					}//end: onPageChange()
				});`

**Comment by jeff-brooks** [comment]
I did find a solution to my problem. By getting my HTML into an ASPX page via the CEWP, I can now make use of the 
`SP.UI.ModalDialog.showModalDialog()`
Function, which allows me to do what I need to do.

Funny thing is I still see the permission denied javascript errors -- but I get but the upload and edit forms and everything does work. 

Perhaps I'll circle back to the javascript errors at a later date.

I sincerely appreciate both the widget and the assistance Paul.

**Comment by purtuga** [comment]
Glad to hear that...

_________
*Paul T*

**Comment by jeff-brooks** [comment]
This ended up being a problem with the version of jquery. I updated my jquery version from 1.10.2 to 1.12.4, and the permission denied problem went away

 See http://stackoverflow.com/a/26469105/6679300  for more info.

**Comment by purtuga** [comment]
Interesting... I would not have expected jQuery to be the culprit... Glad
you figured it out though.. :)

_________
*Paul T*
