### ISSUE TITLE
SPControlUpload file.EncodedAbsUrl always returns 0

### ISSUE THREAD

**Issue by billyjimjack** [purtuga/SPWidgets#74]
No matter what file I upload the file.EncodedAbsUrl always returns 0.  Even though the file object is fully populated with the relevant information.

Here is my code:
![spcontroluploadinitcode](https://cloud.githubusercontent.com/assets/26798756/24516563/c362a8ca-1540-11e7-8050-cf400fb09c97.png)

Here are the calls to load the required javascript:
![spcontroluploadloadedjs](https://cloud.githubusercontent.com/assets/26798756/24516719/4417171c-1541-11e7-80ec-69c09d9ac1e8.png)

Here is a screenshot of the alert returning '0':
![spcontroluploaddonealert](https://cloud.githubusercontent.com/assets/26798756/24516440/32075b64-1540-11e7-8f8b-e167067daef3.png)

Here is a screenshot of the file attributes, at the point of the alert:
![spcontroluploadfileattr](https://cloud.githubusercontent.com/assets/26798756/24516129/402f1ef8-153f-11e7-9110-ee3b4d99bbb5.png)

**Comment by purtuga** [comment]
You must be coming from c# or .net :)

you need to use the `+` sign to concatenate two string together... not the `&`.   So it should be:

```
alert("file url: " + file.EncodedAbsUrl);
```

**Comment by billyjimjack** [comment]
D'OH!  Thanks for the help.
