### ISSUE TITLE
File Upload: Delete Issue

### ISSUE THREAD

**Issue by shankarnss** [purtuga/SPWidgets#80]
Hi Paul,

I was able to implement this tool. File gets uploaded successfully and displays the link to file along with Delete link. Upon clicking Delete i have encountered following issues

1) Page reloads loosing any unsaved data. Why should the page re-load?  How do we prevent this? 
2) File does not get deleted in the document library.

Any idea what am i missing? 

With regards,
Shankar

**Comment by purtuga** [comment]
Hi @shankarnss 
This is a question that falls outside of the scope of my SPWidgets library. The Upload widget I have here does not delete files, so it also sounds like you have created some custom solution.  Sorry that I cant help.
