### ISSUE TITLE
SPDateField Widget - Target Input doesn't empty value

### ISSUE THREAD

**Issue by magicbob93** [purtuga/SPWidgets#81]
Target Input doesn't empty value if Input previously had any value.

Example attached.

OBS: The first input is the target one, the second is the dynamically created input created by the plugin

**Comment by purtuga** [comment]
hi @magicbobxxx  -  I don't see anything attached... Could you please post your code that initializes the date field?
Also, what version of SPWidgets are you using?
(Q. What does "OBS" stand for 😄 )
